module UniTEMPOOrdinaryDiffEqExt

using UniformTEMPO
using OrdinaryDiffEq, LinearAlgebra

"""
    local_channel(t_span::Tuple{<:Number,<:Number}, h_s::Function)


Compute the local channel generated by a time-dependent Hamiltonian.
"""
function UniformTEMPO.local_channel(t_span::Tuple{<:Number,<:Number}, h_s::Function, ::UniformTEMPO.LocalChannelODE)
    dudt(u, p, t) = -im * h_s(t) * u
    u_0 = Matrix{ComplexF64}(I, size(h_s(0)))
    sol = solve(ODEProblem(dudt, u_0, t_span), Tsit5(); saveat=[t_span[end]])
    return kron(transpose(sol.u[1]'), sol.u[1])
end

function __init__()
    UniformTEMPO.local_channel_default_backend[] = UniformTEMPO.LocalChannelODE()
end

end